# Generated by Django 3.0.7 on 2022-10-24 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='car_title',
            new_name='car_title',
        ),
    ]
